### ISSUE TITLE
Apply APAIQ to Plants

### ISSUE THREAD

**Issue by HHH101** [christear/APAIQ_release#1]
Hi~,

First, thank you a lot for your APAIQ tool, the applications are very interesting. 

However I have trouble understanding the "--model" parameter :
I want to explore plants RNA-seq data using APAIQ, but the "deep-learning model" you provided seems to trained by human and animals datasets. Does this model also apply to plants study? Or could you mind helping me train a model for plants ?

Thank you very much in advance,
Danhui

**Comment by Trandamere** [comment]
When will the new version be released? I need it for fungus
