### ISSUE TITLE
Feature (2L:22538087-23513798) beyond the length of 2L size (23513712 bp).

### ISSUE THREAD

**Issue by xinkaitong** [christear/APAIQ_release#11]
I tried to identify polyA sites of 12 RNA-seq samples using the apaiq command, but 5 of them failed to detect. These unsuccessful samples raised an error "Feature (2L:22538087-23513798) beyond the length of 2L size (23513712 bp)". The command is as follows: `${apaiq} \
--input_minus=Control_1_3Signal.Unique.str1.out.bg \
--input_plus=Control_1_3Signal.Unique.str2.out.bg \
--out_dir=${temp} \
--fa_file=${ref} \
--name=Control_1_3 \
--model ${model}/snu398_model.ckpt \
--t 10`
Then, i checked the range of the bedGraph files (Control_1_3Signal.Unique.str1.out.bg and Control_1_3Signal.Unique.str2.out.bg) generated by STAR with the option '--outWigType bedGraph --outWigNorm RPM'. There is no Feature (2L:22538087-23513798) in the bedGraph files, and the range of all features in in the bedGraph files dot beyond the length of 2L size (23513712 bp). I was really confused with what happen. Can author tell me? Thank you very much.

**Comment by xinkaitong** [comment]
> I tried to identify polyA sites of 12 RNA-seq samples using the apaiq command, but 5 of them failed to detect. These unsuccessful samples raised an error "Feature (2L:22538087-23513798) beyond the length of 2L size (23513712 bp)". The command is as follows: `${apaiq} \ --input_minus=Control_1_3Signal.Unique.str1.out.bg \ --input_plus=Control_1_3Signal.Unique.str2.out.bg \ --out_dir=${temp} \ --fa_file=${ref} \ --name=Control_1_3 \ --model ${model}/snu398_model.ckpt \ --t 10` Then, i checked the range of the bedGraph files (Control_1_3Signal.Unique.str1.out.bg and Control_1_3Signal.Unique.str2.out.bg) generated by STAR with the option '--outWigType bedGraph --outWigNorm RPM'. There is no Feature (2L:22538087-23513798) in the bedGraph files, and the range of all features in in the bedGraph files dot beyond the length of 2L size (23513712 bp). I was really confused with what happen. Can author tell me? Thank you very much.

The error is as follows:
![Uploading image.png…]()
The tails of the bedGraph files is as follows:
![Uploading image.png…]()
![Uploading image.png…]()
The length of chromosome 2L size is 23513712 bp, which was calculated using the seqkit software.

**Comment by christear** [comment]
The problem is due to there are reads from the end of the chromosome, while we extend window length to extract sequencing from the reference. I will fix the bugs but it may need some time. The easiest way for you might be removing those lines closed to the end of chromosome. For instance, using this command: awk '$1 == "2L" && $3 < 23513712 - 200'  Control_1_3Signal.Unique.str1.out.bg > Control_1_3Signal.Unique.str1.out.rm.bg and the newly generated bg file should be able to run apaiq without any errors.

**Comment by xinkaitong** [comment]
> The problem is due to there are reads from the end of the chromosome, while we extend window length to extract sequencing from the reference. I will fix the bugs but it may need some time. The easiest way for you might be removing those lines closed to the end of chromosome. For instance, using this command: awk '$1 == "2L" && $3 < 23513712 - 200' Control_1_3Signal.Unique.str1.out.bg > Control_1_3Signal.Unique.str1.out.rm.bg and the newly generated bg file should be able to run apaiq without any errors.

Thank you. It can work well following your suggestion.

**Comment by christear** [comment]
You are welcome
