### ISSUE TITLE
apaiq fails to run

### ISSUE THREAD

**Issue by haibol2016** [christear/APAIQ_release#2]
Hello developer of  Apaiq,

   I tried to run APAIQ using human RNA-seq data as follows:

```
source  ~/miniconda3/etc/profile.d/conda.sh
conda activate apaiq_env

set -euo pipefail

in=results/010.bedtools.bedgraph.out
bedgraph=(`ls $in/SRR15734*.bedgraph`)
sample=(`ls $in/SRR15734*.bedgraph | perl -p -e 's{.+/(.+?).bedgraph}{$1}'`)
genome_fasta=~/mccb-umw/shared/genome/human_gencode_v34/GRCh38.primary_assembly.genome.fa
depth=(140 143 147 139)

model=bin/APAIQ_release/model/snu398_model.ckpt
out=results/027.APAIQ.out/${sample[$i]}
mkdir -p $out

apaiq --out_dir  $out  \
      --input_file   ${bedgraph[$i]} \
      --fa_file     $genome_fasta \
      --model  $model \
      --t 8 \
      --depth  ${depth[$i]} \
      --name   ${sample[$i]}
```

 But I got lots of warnings and error message:
**WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.momentum
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-0.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-0.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-1.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-1.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-2.gamma
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-2.beta
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-3.gamma
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-3.beta
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-4.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-4.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-5.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-5.bias
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-6.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer's state 'momentum' for (root).layer_with_weights-6.bias
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
Traceback (most recent call last):
  File "/home/haibo.liu-umw/miniconda3/envs/apaiq_env/bin/apaiq", line 33, in <module>
    sys.exit(load_entry_point('apaiq==1.0.3', 'console_scripts', 'apaiq')())
  File "/home/haibo.liu-umw/miniconda3/envs/apaiq_env/lib/python3.7/site-packages/apaiq-1.0.3-py3.7.egg/apaiq/APAIQ_v1.py", line 163, in main
  File "/home/haibo.liu-umw/miniconda3/envs/apaiq_env/lib/python3.7/site-packages/apaiq-1.0.3-py3.7.egg/apaiq/postScan.py", line 83, in annotatePAS
NameError: name 'sub_pas' is not defined
**

I think the error occurred in this line: https://github.com/christear/APAIQ_release/blob/main/src_v2/postScan.py#L83.  Could you take a look.

Thank you,

Haibo

**Comment by JoshuaChou2018** [comment]
Bug fixed
