### ISSUE TITLE
How to get pre-trained model and annotation db_file for mouse mm39 ?

### ISSUE THREAD

**Issue by CTLife** [christear/APAIQ_release#7]
You only provided them for human hg38 https://github.com/christear/APAIQ_release/issues/5 

Thanks.

**Comment by christear** [comment]
Sorry for the late reply. Based on what we have tested, there is no obvious difference between using the model trained from mouse data and using the model trained from the human data. We will add the function for training the customized model in the updated version. For the db_file, we united the annotation from GENCODE and PAS from polyA_db. I will also update a db_file for mice (mm10) and you might use 'liftOver' to convert it to mm39.

**Comment by CTLife** [comment]
OK.
