### ISSUE TITLE
what's the difference between model and regression_model ?

### ISSUE THREAD

**Issue by CTLife** [christear/APAIQ_release#8]
pre-trained model for human hg38  you provided : https://drive.google.com/drive/folders/1KpT6Ajm5qqsGm_G-HMdwKBtmrDcDsi0E

pre-trained regression_model for human hg38  you provided :  https://drive.google.com/drive/folders/1KkI4cc04hSb-foVjNcS253kRyj8EYaLL

Which file is for --model ? 
Previously, I used model, but not regression_model, for my human datasets.

**Comment by christear** [comment]
Sorry for the late reply. The model is used to predict PAS, while the regression_model is used to quantify the expression of the provided PAS. Hope this answer could be helpful

**Comment by CTLife** [comment]
Thanks.

**Comment by christear** [comment]
you are welcome
